### ISSUE TITLE
Add proxy configuration support

### ISSUE THREAD

**Issue by guyzmo** [guyzmo/git-repo#105]
reuse the way proxy is configured in git, check http variables (I guess requests does it per default, though) and configure requests to do that.

**Comment by pyhedgehog** [comment]
Additional useful git config variables:
 1. `http.sslverify` and other http.ssl*.
 2. `http.proxyAuthMethod`.
 3. `http.<url>.*` including `http.<url>.proxy`.
 3. `remote.<name>.proxy` (should override on per-remote basis).
