### ISSUE TITLE
move one issue including ints comments from one repository to another

### ISSUE THREAD

**Issue by toogley** [guyzmo/git-repo#111]
Hey.

I think it would be a very useful feature to move issues to a different repository - ideally including all comments made there and such.

That would be especially useful for projects which have one main repository for the code and some other repositories for instance the website. As the main repository is mainly starred and focused one, bugs are also reported there. Of course they may not know what's the best place for filing the bug - therefore i think moving issues around would make sense. If its the wrong repository, it wouldn't have to be closed.

**Comment by guyzmo** [comment]
what do you mean by "moving"? Technically, you cannot move issues between repositories in github… So do you mean copying all infos of an issue onto another?

**Comment by toogley** [comment]
Yeah, i mean copying the issue including all infos onto another repository and deleting the one in the old repo.

**Comment by guyzmo** [comment]
Well, you can't delete an issue

**Comment by toogley** [comment]
Oh, i didn't knew that. Hm, then this idea much less useful, i think. Hm.
