### ISSUE TITLE
Invalid port default for scheme=http

### ISSUE THREAD

**Issue by pyhedgehog** [guyzmo/git-repo#123]
[`port` default](https://github.com/guyzmo/git-repo/blob/9169256aee61c6f818d10370cd0e9f951433041d/git_repo/services/service.py#L174) should depends on `scheme` value as in [`buld_url()`](https://github.com/guyzmo/git-repo/blob/9169256aee61c6f818d10370cd0e9f951433041d/git_repo/services/service.py#L211). It can just default to `None` for `buld_url()` to work correctly.

**Comment by guyzmo** [comment]
yup you're right, I've been stupid here ☺
