### ISSUE TITLE
Error in `list -l` for `gitlab` and `gogs`

### ISSUE THREAD

**Issue by pyhedgehog** [guyzmo/git-repo#124]
```console
# git lab list -l pyhedgehog
Fatal error: 'list' object has no attribute 'format'
```

Format should be `yield`ed in both cases.

**Comment by pyhedgehog** [comment]
For gogs please use following format: `yield "{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{:25}\t{}"` as modification timestamp can be returned by Gogs (depending on environment) either like `"2016-12-27T20:37:35Z"` (20 chars) or like `"2016-12-20T08:50:09+03:00"` (25 chars).

**Comment by guyzmo** [comment]
ok, we should ultimately use a proper date format like I do with github (and `ls` does), i.e.: `Mmm DD (YYYY|HH:mm)`
