### ISSUE TITLE
Get listed on GitHub Developer

### ISSUE THREAD

**Issue by bittner** [guyzmo/git-repo#128]
It's a bit difficult to find this package. I'd appreciate if it were [listed on GitHub Developer](https://developer.github.com/libraries/#python) in the Python third-party libraries.

**Comment by guyzmo** [comment]
it's not exactly a library, and hasn't been designed to be used externally (even though nothing forbids you to do so). It's really focused on being a decend CLI tool.

So I'm not sure it'd belong there, you don't see `gittower` for example or `hub` listed on this page, but you see `github3.py` which is the abstraction being used by `git-repo`.

**Comment by guyzmo** [comment]
Also, I don't know how to submit my own project to such a page, is there some place where this page can be edited?

**Comment by bittner** [comment]
I really have only _looked_ at your project, and it seems to me like something one can use as an interface to manage repository projects on (all) the major version control system services. Yes, it's a CLI, but it offers a nice API abstraction to uniformly manage resources there (same syntax for the same tasks).

I would [submit a support request](https://github.com/contact) and ask GitHub staff to add your project to the list. I can do that for you if you're confident that it deserves a place on that list. (I believe it does.) - It could of course be that they reject the request as it is "not only about" GitHub, but who knows.

**Comment by guyzmo** [comment]
hello @bittner, so have you done that? did you get any feedback? :)

**Comment by bittner** [comment]
No, I did not. It's not difficult, though. Just click on the link above and send a message. They usually respond quickly.

**Comment by guyzmo** [comment]
ok, just did it, we'll see where it goes ☺ thank you

**Comment by guyzmo** [comment]
answer from support:

> *Thanks for reaching out, but that list of libraries has a different purpose. That page lists only wrapper libraries for the GitHub API, it does not list all the possible tools built on top of the API. As far as I can tell, you already recognized this and mentioned it in a comment on the issue you linked to.*
> *Perhaps in the future we'll have a list which mentions all these tools as well, but I can't say when that might happen.*
