### ISSUE TITLE
Use '\\' too as separator when printing help

### ISSUE THREAD

**Issue by sukiletxe** [guyzmo/git-repo#130]
When using `git-repo -h`on Windows, I noticed that the full path is displayed in every command's help. This is because '/' is used as the path separator when calling `sys.argv[0]` (the last item is taken from that split). On Windows, there is no "/", but "\\".

**Comment by guyzmo** [comment]
wha, so git-repo actually works on windows‽ 😀♥

sure I can make a fix for that, using `os.path.sep` instead. Don't hesitate to notify of any other defect you can catch specific to working on windows.

**Comment by sukiletxe** [comment]
Well, to be honest, I just tried the help thing. So I don't know if it actually works. Will report back when I have the chance to test it more.
