### ISSUE TITLE
Failing to create merge request on gitlab.

### ISSUE THREAD

**Issue by michalczaplinski** [guyzmo/git-repo#131]
```
git lab request create user/my-repo myfeature master 'My neat feature' -m 'So much to say about that feature…'
```
fails with:
```
Fatal error: request_create() takes from 6 to 8 positional arguments but 9 were given
```

**Comment by guyzmo** [comment]
here's my reaction to that: 

1. WTF, 😲
2. OMFG, 😲
3. Shame on me 😑

looking into it, and making sure all arguments are well tested.
I have to admit I'm having a hard time figuring out the right amount of automagic is needed to make the `request create` command work.
