### ISSUE TITLE
config should indicate if the service is already setup

### ISSUE THREAD

**Issue by jayvdb** [guyzmo/git-repo#136]
I setup bitbucket, but then pressed ^C during github.
Re-running config prompted me to configure the bitbucket service, and the default was Y, but then it failed.

```
$ git repo config
Do you want to configure the bitbucket service?
    [Yn]> 
Fatal error: A token has been generated for this service. Please revoke and delete before proceeding.
```

IMO the prompt and default should indicate that it is already ready to use.

**Comment by guyzmo** [comment]
indeed, that'd be a good feature! Thank you 👍

**Comment by guyzmo** [comment]
merged in devel!
