### ISSUE TITLE
Renamed gitlab repositories cause incorrect URLs

### ISSUE THREAD

**Issue by jayvdb** [guyzmo/git-repo#137]
https://gitlab.com/coala/package_manager has been given a new name `dependency_management`, but the URL doesnt change.  It is quite confusing and IMO is a misfeature.  But we've done it.

And git-repo doesnt know about this.

```
git lab request coala/package_manager list
List of open requests to merge:
 id	title                                                       	URL
 31	MavenRequirement: Prevent test fails                        	https://gitlab.com/coala/dependency_management/merge_requests/31
 30	DistributionRequirementTest: Fix assertRaisesRegex          	https://gitlab.com/coala/dependency_management/merge_requests/30
 29	GoRequirement: Add missing space to command                 	https://gitlab.com/coala/dependency_management/merge_requests/29
```

These URLs like https://gitlab.com/coala/dependency_management/merge_requests/31 are wrong; they should be https://gitlab.com/coala/package_manager/merge_requests/31 .

**Comment by guyzmo** [comment]
oh, that's painful, I did not know the external URL could be different from the internal name. The same use case in github is that when you rename the project, the URL changes, and the old URL redirects to the new URL.

I'll try to figure out how to fix that, but I also believe this is bad UX from gitlab and if it hasn't been done, you should make an issue on gitlab-ce's issues.

**Comment by guyzmo** [comment]
(also the reason for rebuilding URIs based on project slugs it's because in many parts the gitlab API uses projects IDs instead of the project slugs to identify the projects)
