### ISSUE TITLE
Document 'upstream' special remote

### ISSUE THREAD

**Issue by jayvdb** [guyzmo/git-repo#145]
I learnt in https://github.com/guyzmo/git-repo/issues/143#issuecomment-286090012 that `upstream` is a remote that `git-repo` uses.

It would be useful to document how this special remote is used.

**Comment by guyzmo** [comment]
Indeed documentation can definitely be improved (I got to write a proper sphinx doc and push it to readthedocs), meanwhile you might want to read more about the tool in that article I wrote: http://i.got.nothing.to/code/on/git-repo:_the_utility_for_services/

**Comment by guyzmo** [comment]
I opened an issue about that cf #146

**Comment by jayvdb** [comment]
Remote `upstream` could be mentioned in the README now.

**Comment by guyzmo** [comment]
that's a good idea indeed, and part of the documentation improvement ☺

**Comment by guyzmo** [comment]
I've added a [section on remotes](https://github.com/guyzmo/git-repo#remotes) in the readme, up until I actually write the full extensive sphinx documentation.
