### ISSUE TITLE
Provide a template system for MR title and message

### ISSUE THREAD

**Issue by megawubs** [guyzmo/git-repo#150]
For example I'm working in a gitlab environment where issues are leading and I want to have the text
`Resovle: "[issue title]"` as the title by default and`closes #{issue-number}` as the message. For this to work, we need some sort of templating system with simple if/then and some variables and string regex checks 

Variables (from the top of my head):
- BRANCH_NAME (the name of the branch)
- ASSIGNEE (the username of the one assigned)

Example pseudo template:
```
if(BRANCH_NAME starts with numbers and then a dash*) //it's probably the issue number!
closes #[regex-match]
endif
```

* i'm too tired to find the regex for this.

**Comment by guyzmo** [comment]
I suggest to use [**jinja**](http://jinja.pocoo.org/) to do the templating.

Something like that:

```jinja
{% title, *body = repository.commit().message.split('\n') %}
### Title
{{ title }}

### Body
{{ '\n'.join(body) }}

{% match = re.match(repository.head.name, '^(\d+)') %}
{% if match %}
closes {{ match.groups()[0] }}
{% endif %}
```

**Comment by guyzmo** [comment]
cf #122
