### ISSUE TITLE
Allow multiple remotes from the same service

### ISSUE THREAD

**Issue by masaeedu** [guyzmo/git-repo#151]
It might be too late now to do anything about this without massive breaking changes, but it'd be nice if git-repo used the username/namespace of the repo as the remote name (instead of just `github` or `gitlab` etc.). 

I want to be able to clone a repo using `git hub clone guyzmo/git-repo`, then add as many remotes as I want ad-hoc, e.g:
 - `git hub add masaeedu`
 - `git hub add someotheruser`
 - `git hub add masaeedu/differentlynamedgitrepo`
 - `git bb add bitbucketuser/git-repo-mirror`

etc.  

I'd expect this to create qualified remote names like:
 - `github/guyzmo/git-repo`
 - `github/masaeedu/git-repo`
 - `github/someotheruser/git-repo`
 - `github/masaeedu/differentlynamedgitrepo`
 - `bb/bitbucketuser/git-repo-mirror`

**Comment by guyzmo** [comment]
well, it's already possible, even though the syntax isn't as lean as you'd like it to be!

Here's how:

```shell
git hub add masaeedu/git-repo github/masaeedu/git-repo
 % git hub add masaeedu/git-repo github/masaeedu/git-repo 
Successfully added `masaeedu/git-repo` as remote named `github/masaeedu/git-repo`
 % git hub add someotheruser/git-repo github/someotheruser/git-repo
Successfully added `masaeedu/differentlynamedgitrepo` as remote named `github/masaeedu/differentlynamedgitrepo`
 % git bb add bitbucketuser/git-repo-mirror bb/bitbucketuser/git-repo-mirror
Successfully added `bitbucketuser/git-repo-mirror` as remote named `bb/bitbucketuser/git-repo-mirror`
 % git remote
all
bb/bitbucketuser/git-repo-mirror
github
github/masaeedu/differentlynamedgitrepo
github/masaeedu/git-repo
github/someotheruser/git-repo
```

the syntax is a bit more verbose, though you could make a shell function (or a git alias) like:

```shell
% function git-better-add() { git $1 add $2/$3 }
% git-better-add hub github masaeedu/git-repo
```

if you make it a script in your path (`git-better-add`) you'll be able to call it as `git better-add`. Not as cool as you would like, but still a bit better?

**Comment by masaeedu** [comment]
@guyzmo Ah, didn't know that; thanks. I could write it as a script as you say, but I lose out on all the nice git-repo magic. Perhaps a `.gitconfig` option that lets you specify a command that git-repo will call to build your remote names? Kind of like the customizable refspec for remotes feature in git.

**Comment by guyzmo** [comment]
well, you're losing some magic: the ability to guess for you, but there's not much it can do to guess when you've got multiple projects as remotes for a single service.

Though, all the command accept a repo slug, and thus, as long as your'e using the slugs explicitely, you can do most commands without issues. Besides creating those remotes, or doing automagical guessing of the URIs, git-repo doesn't rely much on them. It's really designed to be your CLI remote control of the projects in the git service.

You still can use `git push all mybranch` to push `mybranch` to all the remotes, or push individually to each.

**Comment by guyzmo** [comment]
could you tell me what use cases you see for the syntax you've imagined?

**Comment by masaeedu** [comment]
@guyzmo It is primarily for collaboration across forks of a single project. I often have to work with someone who is working off an existing fork of a project. E.g. `bob`'s forked `hurrcorp/awesome` on Github to add some functionality, and he gets stuck and needs `carol` to fix his PR. Carol only has a Gitlab account, and likely wants both `hurrcorp/awesome` and `bob/awesome` remotes, in addition to her own. Right now, `git-repo` has the concept of a distinction between `upstream` and `github` or whatever, but it is common for there to be n-way collaboration between multiple remotes with no concept of up, down or sideways.

**Comment by guyzmo** [comment]
Well, git-repo has concept for implicit resolution of the most common use case, which is the upstream ← service remotes. What it means is that I had to make a call in what does the command do when you don't give values.

But that does not mean that in four use case git-repo doesn't help. There, `hurrcorp` did:

```bash
git init .
git hub create awesome --add
git push github master
```

then Bob added some functionality in his own fork:

```bash
git hub clone hurrcorp/awesome
# edits and commits
git hub fork
git push github that-branch
git hub request create
```

then Carol did her own fork on gitlab

```bash
git hub clone hurrcorp/awesome
# edits and commits
git lab create awesome
git push gitlab this-branch
```

then Bob can do

```bash
git lab add carol/awesome gitlab/carol --alone # you do not this remote to be in all
git merge gitlab/carol
```

and done! 🙌

**Comment by masaeedu** [comment]
> then Carol did her own fork on gitlab
> `git hub clone hurrcorp/awesome`

@guyzmo No, Carol needs to fork from *Bob's* repo. She's going to be working on top of Bob's branch. Moreover, while she is working on top of Bob's work, she probably needs to periodically rebase the branch onto `hurrcorp/master` to make sure the branch stays mergeable. This means she needs access to both the `hurrcorp` and `bob` remotes in her local repo.

**Comment by guyzmo** [comment]
ok, then

```bash
git hub clone bob/awesome
git hub add upstream
git co github/that-branch
git co -b this-branch
# edits and commits
git lab create awesome
git push gitlab this-branch
```

All in all, what I really am saying is that you don't have the most common use case, and I don't believe this justifies changing *the default behaviour* which is aimed at 90% of the use cases:

* clone a repository, patch it, fork it, push it, make a PR

then maybe push to another git service transparently (between gitlab ↔ github …). That default behaviour being only how `git-repo` behaves when you don't give it arguments.

That being said, you can still do a lot with the `git add` command and its arguments to handle the way you want to use the tool. But you'll have to give it full arguments. For example, you got:

```
git hub clone hurrcorp/awesome
git hub fork # makes guyzmo/awesome on github
git lab create awesome # makes guyzmo/awesome on gitlab
# then you can add your team:
git lab add alice/awesome gitlab/alice --alone
git hub add bob/awesome github/bob --alone
git bb add charlie/awesome bitbucket/charlie --alone
git gt add donnie/awesome gitea/donnie --alone
git bb add eve/awesome bitbucket/eve --alone
…
```

of course, for each of the above, you'll need to have an account configured, or using git-repo won't help (because it's designed with having the possibility to interrogate the API of each service). Because, if you don't, well, you won't have the `git XX` alias configured (and for some of the commands the URL will be missing or with a non-sane default).

All in all, `git-repo` is a tool that's only a glue between what you can do on a git project management service and your local git repository. It's not meant to replace git. So you can do what you would like to do with git-repo, it's just not the default behaviour (so not automagical) and will require more typing than what you'd wish 😉

**Comment by masaeedu** [comment]
@guyzmo Yes, and typing is just what I want to avoid. Unless it is typing in github issue that pesters project maintainers :). 

At any rate, I understand now the arguments you're supposed to pass to make git-repo work the way I need it. Closing.
