### ISSUE TITLE
Suggestion: Switch out xdg-open for 'gio open'

### ISSUE THREAD

**Issue by fa7ad** [guyzmo/git-repo#159]
xdg-open has been deprecated and the tool suggests using `gio open` instead.

Take a look at [this](https://github.com/github/hub/issues/1473) and the related PR

**Comment by guyzmo** [comment]
hm… that would need a scheme to open an URL in a system agnostic way.

**Comment by fa7ad** [comment]
Try this. Uses one of python's standard libraries.

```python
webbrowser.open('http://whateverurl.com')
```
https://docs.python.org/3/library/webbrowser.html

**Comment by guyzmo** [comment]
I'd be happy to accept a PR for that if you're willing to ☺

you just need to change [this](https://github.com/guyzmo/git-repo/blob/devel/git_repo/services/service.py#L479,L479) 😉

**Comment by fa7ad** [comment]
take a look at the PR #161 . seems to be working on linux (all my computers).
