### ISSUE TITLE
Suggestion: Support "Personal Access Tokens"

### ISSUE THREAD

**Issue by jankeromnes** [guyzmo/git-repo#160]
For users that don't want to give `git-repo` their username and password, it would be nice to support "Personal Access Token" authentication.

For example, I can generate Personal Access Tokens on https://github.com/settings/tokens or https://framagit.org/profile/personal_access_tokens, and I would like `git repo config` to accept them (instead, it keeps asking me for my username and password).

**Comment by guyzmo** [comment]
The config command asks the user for the username/password to actually generate a new token with the right permissions.

**Comment by jankeromnes** [comment]
Ah, that's perfect then, thanks a lot!
