### ISSUE TITLE
"git lab list" only shows 20 repositories 

### ISSUE THREAD

**Issue by rlafuente** [guyzmo/git-repo#165]
Using 1.10.2, when running `git lab list <username>`, I get a list of only 20 repositories, even when I know the user has more. It also states `Total repositories: 20`.

Maybe this has to do with GitLab API query limits?

**Comment by rlafuente** [comment]
There also appears to be a hard limit on the number of commits shown when doing `git lab list <username> -l`; the amount seems to be capped at 20.

**Comment by guyzmo** [comment]
Thank you for your report ! I'll have a look into that shortly! The number of projects and commits are queried through python-gitlab in a rather straightforward way, so I might need to double check python-gitlab implementation and documentation to make sure we get the right values.

**Comment by rlafuente** [comment]
The python-gitlab docs section on [pagination](http://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination) mention this behaviour is to be expected:

> By default GitLab does not return the complete list of items. Use the `all` parameter to get all the items when using listing methods:
>     `all_owned_projects = gl.projects.owned(all=True)`

and

> python-gitlab will iterate over the list by calling the corresponding API multiple times. This might take some time if you have a lot of items to retrieve. This might also consume a lot of memory as all the items will be stored in RAM. If you’re encountering the python recursion limit exception, use `safe_all=True` instead to stop pagination automatically if the recursion limit is hit.

So maybe this is a matter of adding the `safe_all=True` to the GitLab `list` calls?

**Comment by guyzmo** [comment]
yay 👍 sounds like a plan! I also saw that it *might* be possible to get some numbers straight from the API using the [v4 API](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/api/projects.md) using the new `statistics` object.
