### ISSUE TITLE
Dots are replaced by hyphens in the repository path on gitlab.com

### ISSUE THREAD

**Issue by yuhr** [guyzmo/git-repo#167]
When I `git lab create foo/bar.baz`, it shows:

```bash
Successfully created remote repository `https://gitlab.com/foo/bar.baz`, with local remote `gitlab`
```

So I expect that the remote url will be `https://gitlab.com/foo/bar.baz`, but I get `https://gitlab.com/foo/bar-baz`. Every time I created such repository, I correct the repository path on the web UI.

This behavior doesn't happen on GitHub. Is this a technical constraint specific to GitLab API?

Thanks.

**Comment by guyzmo** [comment]
thank you for your report, I'll have a look into it shortly. Looking at [the code](https://github.com/guyzmo/git-repo/blob/devel/git_repo/services/ext/gitlab.py#L38,L44) git-repo's code does not tinkle with the name you give, so it's possible there's an issue with python-gitlab, the library being used for connecting with the gitlab API.

**Comment by guyzmo** [comment]
cf @gpocentek's comment on the other issue: 

```
>>> p = gl.projects.create({'name': 'bar.baz'})
>>> p.web_url
u'http://gitlab.lxd/root/bar-baz'
>>> p = gl.projects.create({'name': 'bar.baz2', 'path': 'bar.baz2'})
>>> p.web_url
u'http://gitlab.lxd/root/bar.baz2'
```
