### ISSUE TITLE
Setup for BitBucket?

### ISSUE THREAD

**Issue by AllanLRH** [guyzmo/git-repo#186]
Hi, I'm having some trouble configuring this for Bitbucket, and hope that someone are up for helping out. While Github andGitlab are working fine, I get an error when i run:

```
$ git bit create AllanLRH/testrepo3
Fatal error: Missing service type for custom service.
```

From my `~/.gitconfig`:

```ini
[gitrepo "bitbucket"]
    username = AllanLRH
    token = AllanLRH.{my_very_secret_password_here}
[alias]
    lab = repo lab
    hub = repo hub
    bit = repo bit
```

Isn't this the README instructions, or did I misunderstand them?

Merry Christmas to all of you :)
Allan

**Comment by guyzmo** [comment]
Hi @AllanLRH,

of course I'm still around to help out ☺

for bitbucket, I indeed forgot to update the part of the readme that talks about the old hack when it did not support tokens. Now bitbucket supports application tokens, and git-repo also supports it.

There are two ways to configure it, either:

* by running `git-repo config` and leave git-repo create and fetch the token (though it's scraping the bitbucket interface, so it might break or have broken…), or
* by logging in bitbucket, go to [the application token page](https://bitbucket.org/account/user/guyzmo/app-passwords) and create a new application token for git-repo, copy it and paste it as value for `token = ` in the `gitrepo "bitbucket"` section.

I'll change the README accordingly for the next release, which is likely to be soon, as we're about to ship gerrit's support!

**Comment by AllanLRH** [comment]
Thanks for the reply!

I updated my gitconfig with the application token (allowed access to everything), but when I run the same command as before, I still get the error.


```ini
[gitrepo "bitbucket"]
    username = AllanLRH
    token = Ref5gyX7Q4kdee6S2zs  ; it's not the real token, but the length is unchanged.
[alias]
    lab = repo lab
    hub = repo hub
    bit = repo bit
```

**Comment by guyzmo** [comment]
ah my bad, I overlooked the error…

The issue is that per default bitbucket is `bb` not `bit`. Of course you can choose to use `bit`, but to do so, you need to modify your configuration as such:

```
[gitrepo "bitbucket"]
    username = AllanLRH
    token = ZZZZZZZZZ
    alias = bit
[alias]
    lab = repo lab
    hub = repo hub
    bit = repo bit
```

the `alias = xxx` part is to setup whatever name is to be used as `git-repo xxx` for the service. I'll have to make a note to improve the error message to say something like: `To configure a custom name for a service try adding 'alias = xxx' to the [gitrepo "service name"] section`, instead of the cryptic `Missing service type for custom service`.

**Comment by AllanLRH** [comment]
Nice, this solved my problem. I'm happy with `git bb`, I just used bit because that's what in the README. Thanks for helping me resolve this ☺︎

---

If other have this problem:

```ini
[gitrepo "bitbucket"]
    username = AllanLRH
    token = Ref5gyX7Q4kdee6S2zs  ; it's not the real token, but the length is unchanged.
[alias]
    lab = repo lab
    hub = repo hub
    bb = repo bb
```

```
$ git bb create AllanLRH/testrepo3
Successfully created remote repository `https://bitbucket.org/AllanLRH/testrepo3`, with local remote `bitbucket`
```

**Comment by AllanLRH** [comment]
There's still some misleading information in the README, but I've made a pull request (GH-187) proposing fixes to those. 

EDIT: Seems like we fell victim to a race condition, and you accepted the PR while I was writing this message. Closing.
