### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Astrak** [guyzmo/git-repo#192]
Hi, thanks for this great repo, it is more than efficient and helpful. However I am using it with other tools on top of Git, and the naming is not very creative between them all, no to say confusing:

- Google has this Gerrit tool called [git-repo](https://gerrit.googlesource.com/git-repo/), that uses the command `repo`. It is wisely used for Android, Wikipedia and few other big names involving multi-repository projects. It is not possible to distinguish the tags on StackOverflow for example, since they have the very same name.

- GitHub has [hub](https://github.com/github/hub) that widely recommends aliasing `git` to `hub`. Managing hub with this git-repo turns confusing.

Has some thoughts already been given to this situation?

**Comment by guyzmo** [comment]
for the first one, I've been thinking on renaming the tool `git-services`. It was planned for v2.0, but I don't have a lot of time to work the roadmap up to 2.0 and sadly it's only in my todo list :)

on the second thing, you can override the alias in the configuration with whatever you want.
Though, as `hub` and `git-repo` are serving the same purpose (with `git-repo` doing more than just `github`), it's not likely people will use both at the same time, and use the `git hub` alias with either one or the other… So I believe the default to `hub` is fine! ☺
