### ISSUE TITLE
Fatal error: list index out of range for Python 3.6

### ISSUE THREAD

**Issue by schollii** [guyzmo/git-repo#197]
pip3 install git-repo
git repo config
Do you want to configure the bitbucket service?
    [Yn]> 
Is your service self-hosted?
    [yN]> 
Please enter your credentials to connect to the service:
username> me@someplace.com
password> 
» Login to bitbucket…
Fatal error: list index out of range

**Comment by guyzmo** [comment]
hello @schollii could you rerun with -v ?

the bitbucket authentication process is a real dirty hack, and it's likely they changed the login page (it's basically scraping the actual login page, as they did not provide an API for that).

Don't hesitate to have a look at [that part](https://github.com/guyzmo/git-repo/blob/devel/git_repo/services/ext/bitbucket.py#L370,L460), fix it accordingly and make a PR.

If you don't want/cannot/don't have time to do that, you can still get the token and [set it up manually](https://github.com/guyzmo/git-repo#configuration) in the `.gitconfig` file.

**Comment by guyzmo** [comment]
I just checked the new login of bitbucket, it's now an openid global to atlassian. I should totally disable bitbucket auto configuration, as it cannot work anymore. Though you should still be able to generate a token and use it when added manually to the configuration file.

**Comment by guyzmo** [comment]
Though there's a little hope with https://github.com/atlassian-api/atlassian-python-api that we could connect and generate the token using that API. But let's not have too much hopes.

cf #199
