### ISSUE TITLE
fatal: manifest 'default.xml' not availabl

### ISSUE THREAD

**Issue by MenuuTUX** [guyzmo/git-repo#201]
Okay so I was trying to clone a android recovery and I got a fatal error :

############################################################################################

aqua@aqua-HP-EliteBook-8460p:~/RedWolf$ repo init -u git://github.com/RedWolfRecovery/rw_manifest.git -b rw
Downloading Repo source from https://gerrit.googlesource.com/git-repo
Downloading manifest from git://github.com/RedWolfRecovery/rw_manifest.git
remote: Enumerating objects: 1294, done.
remote: Total 1294 (delta 0), reused 0 (delta 0), pack-reused 1294
fatal: manifest 'default.xml' not available
fatal: invalid "path": TeamWin/.repo/frameworks/base: bad component: .repo

#############################################################################################

How do I solve this?

**Comment by guyzmo** [comment]
Hello, it's sadly very likely that the gerrit implementation is outdated, the best way would be to make a PR to update the gerrit implementation, update any issues and I'd be happy to help with that ☺
