### ISSUE TITLE
Fatal error: Project creation supported for authentified user only!

### ISSUE THREAD

**Issue by ndarilek** [guyzmo/git-repo#44]
Getting the above error when running `git hub create ndarilek/projectname`. Is there some separate authentication step I need to perform? I ran quickstart and expected that would do it.

Thanks.

**Comment by guyzmo** [comment]
Hm… it's supposed to be working. Could you run the command again with `-vvvvv` (yup 5 verbose to have it all)?

Though I'm pretty sure it's related to an issue that has been fixed by #41. I was about to merge it earlier today, and I'll do it as soon as I physically can.

**Comment by smacke** [comment]
+1 i have this issue too

**Comment by smacke** [comment]
Here's the verbose output:

`{'--add': False,
 '--alone': False,
 '--branch': None,
 '--clone': False,
 '--config': None,
 '--force': False,
 '--help': False,
 '--message': None,
 '--path': '.',
 '--secret': False,
 '--tracking': None,
 '--verbose': 5,
 '<branch>': None,
 '<description>': None,
 '<gist>': None,
 '<gist_file>': None,
 '<gist_path>': [],
 '<local_branch>': None,
 '<name>': None,
 '<remote_branch>': None,
 '<request>': None,
 '<target>': 'hub',
 '<title>': None,
 '<user>/<repo>': 'smacke/project',
 'add': False,
 'clone': False,
 'config': False,
 'create': True,
 'delete': False,
 'fetch': False,
 'fork': False,
 'gist': False,
 'list': False,
 'ls': False,
 'open': False,
 'request': False}
send: b'GET /user HTTP/1.1\r\nHost: api.github.com\r\nConnection: keep-alive\r\nUser-Agent: github3.py/0.9.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/vnd.github.v3.full+json\r\nContent-Type: application/json\r\nAccept-Charset: utf-8\r\nAuthorization: token 0eecf1a364c316d31a7f7b7f00a5e74d7e08c53b\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
Fatal error: Project creation supported for authentified user only!
------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/git_repo/repo.py", line 511, in main
    return GitRepoRunner(args).run()
  File "/usr/local/lib/python3.5/site-packages/git_repo/kwargparse.py", line 68, in run
    return self._action_dict[frozenset(args)](self)
  File "/usr/local/lib/python3.5/site-packages/git_repo/repo.py", line 341, in do_create
    service.create(self.user_name, self.repo_name, add=self.add)
  File "/usr/local/lib/python3.5/site-packages/git_repo/services/ext/github.py", line 37, in create
    raise NotImplementedError("Project creation supported for authentified user only!")
NotImplementedError: Project creation supported for authentified user only!
header: Server header: Date header: Content-Type header: Transfer-Encoding header: Status header: X-RateLimit-Limit header: X-RateLimit-Remaining header: X-RateLimit-Reset header: Cache-Control header: Vary header: ETag header: Last-Modified header: X-OAuth-Scopes header: X-Accepted-OAuth-Scopes header: X-GitHub-Media-Type header: Access-Control-Expose-Headers header: Access-Control-Allow-Origin header: Content-Security-Policy header: Strict-Transport-Security header: X-Content-Type-Options header: X-Frame-Options header: X-XSS-Protection header: Vary header: X-Served-By header: Content-Encoding header: X-GitHub-Request-Id`

**Comment by guyzmo** [comment]
Beware of not leaking your Authorization key in comments (I edited your comment to remove it). It looks like it's the bug that's supposed to be fixed by #41.

**Comment by guyzmo** [comment]
I just merged it, along with a few other improvements, and published it as version 1.7.4. 

So: 
```
pip install --upgrade 1.7.4
```

Please check that it's fixed for you!

**Comment by smacke** [comment]
Looks like it's working now; thanks and thanks for catching the authorization key mistake!
