### ISSUE TITLE
provider prompt ordering

### ISSUE THREAD

**Issue by roobert** [guyzmo/git-repo#48]
Thanks for the great tool!

Re-running `git repo config` has the potential to leak credentials since it seems to randomise which provider it prompts for input for first.

If a lazy user (such as myself) isn't careful and doesn't re-read the prompts on each run due to expecting the order to be the same (as is usually the case for wizards) then it's possible to input the credentials for a provider other than the one you're expecting. The result is that secrets are potentially submitted to the wrong provider which is probably a security concern.

**Comment by guyzmo** [comment]
sure, you're making a good point. I actually found that issue being a fun side effect, without considering the potential issue here. Mostly because I don't see the users running `git repo config` more than once ☺

**Comment by guyzmo** [comment]
👍 thank you for your report, it's fixed and it'll be included in the next release I'll push!

**Comment by roobert** [comment]
@guyzmo, thanks again for the great project and quick response :+1:
