### ISSUE TITLE
git repo <target> ls for listing a user's repositories

### ISSUE THREAD

**Issue by WillemMali** [guyzmo/git-repo#50]
I would really like functionality to get a list of all git repos under a given account, preferably in a format easy to parse in scripts and with multiple formatting options (i.e. format as git ssh urls, format as https urls, append default branch or not).

I'm currently using a hand-rolled tool (chegit) to keep my local changes synced to Gitlab, but I don't have tooling for multiple remotes yet (your 'all' remote would solve this), and I don't have a way of getting a list of remote repositories that I might want to keep a local copy of.

Is this functionality already included and did I overlook it in the help page, and if not, would you consider implementing it?

**Comment by WillemMali** [comment]
Some information I would find useful to enumerate:

* repo name (i.e. git-repo)
* (user|group)/repo (i.e. guyzmo/git-repo)
* trivial/user-defined repo name (i.e. Git Repo)
* https clone url
* SSH clone url
* default branch
* visibility (private/internal/public)

Just (user|group)/repo could work, if there's a separate function to get other info based on this ID.

**Comment by guyzmo** [comment]
nope, it's still not implemented. I'm marking this as a feature request, and I'm open for anyone to tackle this. Currently my priority, feature-wise, is on finishing up the *merge request* and *snippets* features for gitlab and bitbucket, as well as adding OAuth support for bitbucket… Otherwise I'm fixing all bugs that are being found!

**Comment by guyzmo** [comment]
Actually I had a thought about that, and I've implemented a first trial of that idea, which works only for github:

``` bash
git hub ls WillemMali
WillemMali/cacka.net              WillemMali/dpkg-rdm               WillemMali/salt-cacka
WillemMali/debian-packaging       WillemMali/guides                 WillemMali/salt-desktop
WillemMali/docker-bootstrap       WillemMali/linux                  WillemMali/site-willemmali-com
WillemMali/docker-dpkg            WillemMali/llvm-kaleidoscope      WillemMali/tools
WillemMali/docker-playground      WillemMali/rust-coreutils         WillemMali/vagrant-cyc0
WillemMali/docker-salt            WillemMali/rust-guessing          WillemMali/vagrant-dpkg-rdm
WillemMali/docker-willemmali-com  WillemMali/rust-hello             WillemMali/vagrant-salt
WillemMali/dotfiles               WillemMali/rust-iup               WillemMali/willemmali.github.io
WillemMali/dpkg-iup               WillemMali/salt-bootstrap
% git hub ls -l
Status  Commits Reqs    Issues  Forks   Coders  Watch   Likes   Lang    Modif           Name
        1       0       0       0       1       0       0       ?       Sep 25 17:06    WillemMali/cacka.net
        16      0       0       1       2       0       0       ?       Jul 22 11:01    WillemMali/debian-packaging
        3       0       0       0       1       0       0       Shell   Jul 23 20:35    WillemMali/docker-bootstrap
        10      0       0       0       1       0       0       Shell   Aug 10 07:23    WillemMali/docker-dpkg
        3       0       0       0       1       0       0       Shell   Aug 10 07:28    WillemMali/docker-playground
        3       0       0       0       1       0       0       ?       Jul 28 17:22    WillemMali/docker-salt
        2       0       0       0       1       0       0       ?       Sep 04 10:45    WillemMali/docker-willemmali-com
        102     0       0       0       1       0       0       Shell   May 23 18:52    WillemMali/dotfiles
        2       0       0       0       1       0       0       ?       Jul 26 10:40    WillemMali/dpkg-iup
        4       0       0       0       1       0       0       ?       Jul 26 10:40    WillemMali/dpkg-rdm
        13      0       0       0       1       0       0       ?       Aug 10 14:58    WillemMali/guides
```

it's still far from perfect, as the `--long` version is slow (to get some useful stats data, I need to query some iterators to count it… counter-productive!), it's abusing the API, and does not list everything.

Also it lacks tests. But that's a start to think about how the UI should look like, and what the UX should be. Maybe some more parameters should be given to add sorting or change the output?

**Comment by guyzmo** [comment]
You can look at my change in this commit 3f9185752458e1e3fc842f1fa34ad0bc3be6ed96 and check it out with the branch [features/list_repos](https://github.com/guyzmo/git-repo/tree/features/list_repos)
