### ISSUE TITLE
git repo <target> create for group/organisations namespaces

### ISSUE THREAD

**Issue by WillemMali** [guyzmo/git-repo#51]
When creating a git repo for a group at Gitlab, I would want to call git-repo with the arguments `lab create <groupname>/<reponame>`, but this results in the repo being created for my current user, and not for the group.

**Comment by guyzmo** [comment]
hum… that's a use case I did not include **YET** in my implementation, I'm sorry ☹ And my bad, I forgot to document that both in the help and the README.

It's definitely a must have feature, so let me change the ticket title to look more like a feature request.

**Comment by guyzmo** [comment]
I'll consider implementing it for github in 1.7, and deliver it in 1.8 for gitlab (and 1.9 for bitbucket).

**Comment by guyzmo** [comment]
oh, looking again at [the code](https://github.com/guyzmo/git-repo/blob/master/git_repo/services/ext/gitlab.py#L32,L33) it looks like there's an issue with the library I'm using that does not enable one to create a repository outside of the user's namespace.

It'd be a good idea to look again at this and see what's going wrong.
