### ISSUE TITLE
Repo name detection breaking when ".git" is in the repo url

### ISSUE THREAD

**Issue by Crazybus** [guyzmo/git-repo#55]
If the repo name can't be detected _guess_repo_slug is checking to see if `.git` is anywhere in the repo name instead of checking at the end of the string. This then truncates the repo name by removing the last 4 characters.

Example `git@test.gitlab.com:project/git_repo` becomes `git@test.gitlab.com:project/git_`

I'm going to submit a pull request with the fix.

**Comment by guyzmo** [comment]
OMG! Good catch 😀
Shame on me for such a stupid bug /o\
