### ISSUE TITLE
Support for GitHub appliances

### ISSUE THREAD

**Issue by kozmikyak** [guyzmo/git-repo#60]
University of Minnesota uses a local GitHub appliance instead of public GitHub.  Would be fantastic to get this working against it.

**Comment by guyzmo** [comment]
I'd be very happy to add such a feature, but sadly I have no access to such appliance, I have no idea what would be the differences with `github.com`, and how to write tests for them.

So I'd be happy to accept a PR to integrate it (basically adding the `fqdn = ` feature there already is for gitlab), or write a patch if I'm given access to one appliance (is github hosting an accessible test instance somewhere?).

**Comment by kozmikyak** [comment]
I'll see about both options--I can try my hand at just adding an FQDN option, and seeing if replacing "github.com" with it everywhere "just works".  And I can see about whether we can grant any access.  It would be difficult, though, as our GitHub appliance authenticates against our LDAP here at the U and there are politics involved.

I'd also be curious whether there's the possibility to test an appliance--perhaps they can make a virtual machine image available somehow for that?  That would come in handy here at the U even beside the point of us wanting this awesome tool.  :->

**Comment by guyzmo** [comment]
@kozmikyak did it work?

**Comment by guyzmo** [comment]
ok, no news for a while, I'll consider it's working, as anyway I have no ways to actually test it.

Reopen if needed!
