### ISSUE TITLE
Not working after pip3 install git-repo

### ISSUE THREAD

**Issue by chmike** [guyzmo/git-repo#65]
I followed the installation instructions in the Readme file. 
After installation, `git repo config` is not recognized by git as a valid git command. Same problem with `git hub`. 

There is apparently a missing installation step in the documentation.

**Comment by guyzmo** [comment]
The `pip install` command installs the `git-repo` executable in the path. Then `git` has a wonderful feature that makes any command starting with `git-` a subcommand of git (so `git-repo` or `git repo` are actually the same thing).

So either you missed a failure in the `pip install` command or it did succeed but it has been installed in a bin directory out of your `$PATH`.

What is your system? What is your pip version? And can you paste the `pip3 install git-repo` output (you can `pip uninstall git-repo` first)?

**Comment by chmike** [comment]
Ah yes. Found it. pip3 install stores the binary in `./.local/bin` witch is not in my path. I'll add it. 
I'm using Ubuntu 16.04 (LTS) and the default python configuration. 
I had to update pip3 because the default is outdated. 

Adding a line in the README about adding this directory in the path would be helpful. Python programmers would already have it. I didn't. 

Here is what I added to my `.bash_aliases` file
```
 # set PATH so it includes python's private bin if it exists
if [ -d ~/.local/bin ] ; then
    PATH="${PATH}":~/.local/bin
fi
```
I hope this is correct bash because I'm not an expert.

**Comment by guyzmo** [comment]
Well, your bit of script looks correct. Though, if it installs in there, it's likely that you have a configuration setting forcing the `--user` scheme, something like:

```
[install]
user=true
```

in `~/.pip/pip.conf`…
