### ISSUE TITLE
Error in add feedback message

### ISSUE THREAD

**Issue by chmike** [guyzmo/git-repo#67]
This is what I experienced:
```
$ git repo hub add chmike/test origin
Successfully added `chmike/test` as remote named `github`
$ git remote -v
all	git@github.com:chmike/test (fetch)
all	git@github.com:chmike/test (push)
origin	git@github.com:chmike/test (fetch)
origin	git@github.com:chmike/test (push)
```
1. The feedback message say that a remote named `github` has been added where in fact it is named `origin`. 
2. Where is this `all` remote coming from ? I didn't ask for it. Why is it for ?

Here is more verbose output
```
$ git hub -vv add chmike/test test
> git remote get-url --all all
> Popen(['git', 'remote', 'get-url', '--all', 'all'], cwd=/tmp/test, universal_newlines=False, shell=None)
> git remote add test git@github.com:chmike/test
> Popen(['git', 'remote', 'add', 'test', 'git@github.com:chmike/test'], cwd=/tmp/test, universal_newlines=False, shell=None)
Successfully added `chmike/test` as remote named `github`
```

Once an `all` remote has been defined, git-repo does a `git remote get-url --all all`.

**Comment by chmike** [comment]
Looking at the code I see that all should group all the remote url so that it is possible to push to all remote. That is smart and useful.

**Comment by guyzmo** [comment]
About the `all` there is [a little explanation in my blog](http://i.got.nothing.to/code/on/git-repo:_the_utility_for_services/#choices-made), I'll publish soon an article about the `all` remote trick, though it's definitely missing from the README.

**Comment by guyzmo** [comment]
and thank you for the bad remote reporting, I'll fix that.

**Comment by guyzmo** [comment]
narrowed the issue to what the bug is. Closing this one ☺

Thanks for your report 🍺
