### ISSUE TITLE
Error:  'GithubService' object has no attribute 'username'

### ISSUE THREAD

**Issue by chmike** [guyzmo/git-repo#69]
I created an empty git repository. When I try to create a project on github it fails with an error.
Apparently the python object is missing the username member variable. 

```
$ git hub create chmike/test
Fatal error: 'GithubService' object has no attribute 'username'
```

With debug info

```
$ git-repo hub -vvv create chmike/test
Fatal error: 'GithubService' object has no attribute 'username'
------------------------------------
Traceback (most recent call last):
  File "/home/meessen/.local/lib/python3.5/site-packages/git_repo/repo.py", line 522, in main
    return GitRepoRunner(args).run()
  File "/home/meessen/.local/lib/python3.5/site-packages/git_repo/kwargparse.py", line 68, in run
    return self._action_dict[frozenset(args)](self)
  File "/home/meessen/.local/lib/python3.5/site-packages/git_repo/repo.py", line 352, in do_create
    service.create(self.user_name, self.repo_name, add=self.add)
  File "/home/meessen/.local/lib/python3.5/site-packages/git_repo/services/ext/github.py", line 37, in create
    if user != self.username:
AttributeError: 'GithubService' object has no attribute 'username'
```

**Comment by guyzmo** [comment]
ok, it definitely looks like an edge case bug, but it should work if you try: `git hub create test` (no need for the username when it's yours).

I'll try to replicate and fix it.

**Comment by chmike** [comment]
Unfortunately my account name is not chmike. So I can't test it.

It's the filename to the private key that we have to put in the token config parameter for github ?
Is it the same for gitlab ? Even a simple remote add fails with gitlab because of private key error.

**Comment by guyzmo** [comment]
please keep discussion about one issue per ticket.

**Comment by guyzmo** [comment]
> Unfortunately my account name is not chmike. So I can't test it.

I don't understand, you're @chmike, so your account name actually is chmike… and if you do:

```
git hub create test
```

it should create a repository under the chmike name.

**Comment by guyzmo** [comment]
About the private keys, it's not a filename, just a copy/paste of the authentication token you can setup at this URL:

https://github.com/settings/tokens

**Comment by chmike** [comment]
This explains the confusion about the username. I expect the token identifies the username. 

Unfortunately I don't feel Ok using these tokens which are stored in clear text in git config files. I'll stick to ssh with public/private key identification.

**Comment by guyzmo** [comment]
> I expect the token identifies the username. 

the token actually does identify the username, it's just that for some reason you've found an edge case I did not test for, when creating a project under your own name ☺.

> Unfortunately I don't feel Ok using these tokens which are stored in clear text in git config files. I'll stick to ssh with public/private key identification. 

Those are unrelated, and your rationale is wrong. 

The SSH keys are *only* for doing pure git stuff, fetching the remotes, the branches and the commits.

On the other hand, the Private Key is a convenience to grant a tool (such as *git-repo*) control over what it can do with your github or gitlab accounts (for bitbucket, there's no privatekeys and it's still storing login+password which is *wrong*).

The difference between a private key and your full account credentials, is that it's designed to make it hard — if not impossible — to take over an account using only the private key. And also, make it easy to revoke a key (given that you've lost your laptop, phone… that had such a key).

The difference between your private key, and the public/private key scheme of SSH is that the private key is a shared secret given to you by github once you're authenticated using your real credentials (and 2FA if neabled), whereas you give github your public key to authenticate yourself when doing git operations. But in both cases, you do have a cleartext version of a secret (the SSH private key in `~/.ssh/id_rsa` or the shared secret token).

That being said, storing secrets in `~/.gitconfig` is debatable and there's a ticket, #63 about that issue. As a temporary patch, if you refuse to put secrets in `~/.gitconfig` you can set your keys using environment variables:

``` bash
export PRIVATE_KEY_GITHUB=XXXX
export PRIVATE_KEY_GITLAB=YYYY
export PRIVATE_KEY_BITBUCKET=login:password
git hub create test
```

**Comment by guyzmo** [comment]
ok I consider this issue closed, as I made another narrowed issue on the misleading traceback for a legitimate error.
