### ISSUE TITLE
Display website url instead of api url for pull requests

### ISSUE THREAD

**Issue by Bubu** [guyzmo/git-repo#93]
Right now `git hub request curl/curl list` displays the following url https://api.github.com/repos/curl/curl/issues/1207.
I think it should instead display the url to the website to the pull request, which would be: `https://github.com/curl/curl/issues/1207`

**Comment by guyzmo** [comment]
damn… I forgot to include that one in 1.8.1. I pushed a fix for that it'll be with the next release, I promise! ☺
