### ISSUE TITLE
Unable to clone GitLab repos

### ISSUE THREAD

**Issue by AluisioASG** [guyzmo/git-repo#97]
I seem to be hitting a race in `GitlabService`'s initialization:
```
$ git repo -v lab clone guyzmo/git-repo
Traceback (most recent call last):
  File "…/git_repo/repo.py", line 347, in do_clone
    service = RepositoryService.get_service(repository, self.target)
  File "…/git_repo/services/service.py", line 126, in get_service
    cls._current = service(repository, config)
  File "…/git_repo/services/ext/gitlab.py", line 22, in __init__
    super().__init__(*args, **kwarg)
  File "…/git_repo/services/service.py", line 168, in __init__
    self.connect()
  File "…/git_repo/services/ext/gitlab.py", line 26, in connect
    self.gl.set_url(self.url_ro)
AttributeError: 'GitlabService' object has no attribute 'gl'
```

A brief look at the code suggests the problem lies in the execution order:
- `GitlabService.__init__` calls `RepositoryService.__init__`
  - `RepositoryService.__init__` initializes `RepositoryService.insecure`
  - `RepositoryService.__init__` calls `GitlabService.connect`
    - `GitlabService.connect` accesses `GitlabService.gl`
- `GitlabService.__init__` initializes `GitlabService.gl` using `RepositoryService.insecure`

The other services swap the two lines in the constructor, but here we can't do that.

I'm using git-repo 1.8.0 on Python 3.6, installed via `pip install --user git-repo`. `list` and `create` both work fine.

**Comment by guyzmo** [comment]
great, I actually discovered that bug yesterday… and I still haven't had time to debug that. But I've started looking at it, and so far I'm at stage 3 of [the six stages of debugging](http://mwcremer.blogspot.fr/2007/06/six-stages-of-debugging.html).

BTW, snippets are also 👌 but requests are broken.

What I don't understand is:

1. that it's not being caught by tests, and 
2. why did'nt it happen sooner?

**Comment by AluisioASG** [comment]
In the tests, [the service is created without a repository, which is set afterwards](https://github.com/guyzmo/git-repo/blob/9c2c4f43d4aa32b55b79556472a34fc1f3dbfa5b/tests/helpers.py#L381-L389). [do_clone passes the repository to the service constructor](https://github.com/guyzmo/git-repo/blob/9c2c4f43d4aa32b55b79556472a34fc1f3dbfa5b/git_repo/repo.py#L339-L347), thus triggering the issue.

**Comment by guyzmo** [comment]
ok you've now answered the stage ③, and even ④ Now let's get to the '*⑤ oh, I see*' stage.

**Comment by guyzmo** [comment]
and ten minutes later, after pouring a cup of coffee…  ☕

there it goes:

> `GitlabService.__init__` initializes `GitlabService.gl` using `RepositoryService.insecure`

*"Oh, I see".*

the patch is easy, and I'll push it today, just make init right again, and set `ssl_verify` in `connect()`:

```
    def __init__(self, *args, **kwarg):
        self.gl = gitlab.Gitlab(self.url_ro)
        super().__init__(*args, **kwarg)

    def connect(self):
        self.gl.ssl_verify = self.insecure
        […]
```

And now we're getting to:

* ⑥ *how did that ever work?* 

actually it did not since I added support of the insecure configuration option).

**Comment by guyzmo** [comment]
@AluisioASG if you could check out PR #98 (or branch `/fix/issues/97`) and tell me if it's working fine for you, it'd be great. Also thank you for the detailed report!

**Comment by AluisioASG** [comment]
Works now, aside from `ssl_verify`. Thanks!
